### ISSUE TITLE
Cannot be closed

### ISSUE THREAD

**Issue by AZHenley** [utk-cs/CS340-Fall-2021#142]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by robobenklein** [comment]
Yes. asdf indeed.

**Comment by solsane** [comment]
bruuhh

**Comment by bepri** [comment]
This is a fantastic change! Nice work.

**Comment by Jamin11** [comment]
indeed

**Comment by willnjohnson** [comment]
Test test test

**Comment by dearvarun** [comment]
Duplicate issue, see issue #0.

**Comment by FueledByPants** [comment]
Ironically asking for Bonus Points here, I know its shameless

**Comment by LexiVelas** [comment]
Lovely work good chap!

**Comment by e-vananderson** [comment]
lgtm!

**Comment by SKBlank** [comment]
poggies

**Comment by bepri** [comment]
everyone in the class laughed at me :(

**Comment by 1480c1** [comment]
> 
> 
> everyone in the class laughed at me :(

Thanks bot, your contributions are always welcome.

**Comment by AZHenley** [comment]
1c2660c

**Comment by LexiVelas** [comment]
NO DON'T CLOSE ME

**Comment by dearvarun** [comment]
F

**Comment by FueledByPants** [comment]
YOU CANNOT SILENCE US

**Comment by bepri** [comment]
**I am unstoppable**

**Comment by FueledByPants** [comment]
what now

**Comment by bepri** [comment]
i say we make this a chatting board

dearvarun was here
NO TEST, ONLY DO

**Comment by dearvarun** [comment]
You can edit other people's messages
I HAVE INFINITE POWER

**Comment by AZHenley** [comment]
@ParkerNC extra homework for you to complete: https://tiny.utk.edu/homework
